# This is a basic workflow to help you get started with Actions

name: Unit Test Status Check
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  api_unit_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: API Unit Tests
      run: |
        cd api
        python -m pip install --upgrade pip
        make test
  npm_unit_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 15.1
        cache: 'npm'
    - run: npm install
    - run: npm run test:unit